//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.544
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AndroidClient
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int MvxBind = 2130771968;
			
			// aapt resource value: 0x7f010002
			public const int MvxDropDownItemTemplate = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int MvxHttpSource = 2130771971;
			
			// aapt resource value: 0x7f010001
			public const int MvxItemTemplate = 2130771969;
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int appbar_database = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int appbar_home = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Tab_Sessions = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Tab_Welcome = 2130837508;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f04000e
			public const int LoadingText = 2130968590;
			
			// aapt resource value: 0x7f040001
			public const int MvxBindableListItemTagUnique = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int MvxBindingTagUnique = 2130968576;
			
			// aapt resource value: 0x7f04000c
			public const int button1 = 2130968588;
			
			// aapt resource value: 0x7f04000b
			public const int editText1 = 2130968587;
			
			// aapt resource value: 0x7f04000a
			public const int tab1 = 2130968586;
			
			// aapt resource value: 0x7f04000d
			public const int tab2 = 2130968589;
			
			// aapt resource value: 0x7f040009
			public const int tabHost = 2130968585;
			
			// aapt resource value: 0x7f040002
			public const int textView1 = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int textView2 = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int textView3 = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int textView4 = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int textView5 = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int textView6 = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int textView7 = 2130968584;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Detail_ViewModel = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int DetailView = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int MainView = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Result_ViewModel = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ResultView = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int SplashScreen = 2130903045;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int ApplicationName = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int Loading = 2131034113;
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MvxBindableListView = new int[] {
					2130771969,
					2130771970};
			
			// aapt resource value: 1
			public const int MvxBindableListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxBindableListView_MvxItemTemplate = 0;
			
			public static int[] MvxBinding = new int[] {
					2130771968};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			public static int[] MvxHttpImageView = new int[] {
					2130771971};
			
			// aapt resource value: 0
			public const int MvxHttpImageView_MvxHttpSource = 0;
			
			private Styleable()
			{
			}
		}
	}
}
