//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.17929.
// 
#pragma warning disable 1591

namespace Core.PhraseReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IPhraseService", Namespace="http://tempuri.org/")]
    public partial class PhraseServiceClient : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback DisplayPhrasesOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreatePhraseOperationCompleted;
        
        private System.Threading.SendOrPostCallback EditPhraseOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeletePhraseOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public PhraseServiceClient() {
            this.Url = "http://192.168.75.10:59027/WebServices/PhraseService.svc";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event DisplayPhrasesCompletedEventHandler DisplayPhrasesCompleted;
        
        /// <remarks/>
        public event CreatePhraseCompletedEventHandler CreatePhraseCompleted;
        
        /// <remarks/>
        public event EditPhraseCompletedEventHandler EditPhraseCompleted;
        
        /// <remarks/>
        public event DeletePhraseCompletedEventHandler DeletePhraseCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IPhraseService/DisplayPhrases", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/PopCornOneWebApp.Models")]
        public Phrase[] DisplayPhrases() {
            object[] results = this.Invoke("DisplayPhrases", new object[0]);
            return ((Phrase[])(results[0]));
        }
        
        /// <remarks/>
        public void DisplayPhrasesAsync() {
            this.DisplayPhrasesAsync(null);
        }
        
        /// <remarks/>
        public void DisplayPhrasesAsync(object userState) {
            if ((this.DisplayPhrasesOperationCompleted == null)) {
                this.DisplayPhrasesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDisplayPhrasesOperationCompleted);
            }
            this.InvokeAsync("DisplayPhrases", new object[0], this.DisplayPhrasesOperationCompleted, userState);
        }
        
        private void OnDisplayPhrasesOperationCompleted(object arg) {
            if ((this.DisplayPhrasesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DisplayPhrasesCompleted(this, new DisplayPhrasesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IPhraseService/CreatePhrase", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CreatePhrase([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Phrase phrase, out int CreatePhraseResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool CreatePhraseResultSpecified) {
            object[] results = this.Invoke("CreatePhrase", new object[] {
                        phrase});
            CreatePhraseResult = ((int)(results[0]));
            CreatePhraseResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void CreatePhraseAsync(Phrase phrase) {
            this.CreatePhraseAsync(phrase, null);
        }
        
        /// <remarks/>
        public void CreatePhraseAsync(Phrase phrase, object userState) {
            if ((this.CreatePhraseOperationCompleted == null)) {
                this.CreatePhraseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreatePhraseOperationCompleted);
            }
            this.InvokeAsync("CreatePhrase", new object[] {
                        phrase}, this.CreatePhraseOperationCompleted, userState);
        }
        
        private void OnCreatePhraseOperationCompleted(object arg) {
            if ((this.CreatePhraseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreatePhraseCompleted(this, new CreatePhraseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IPhraseService/EditPhrase", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void EditPhrase([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Phrase phrase, out bool EditPhraseResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool EditPhraseResultSpecified) {
            object[] results = this.Invoke("EditPhrase", new object[] {
                        phrase});
            EditPhraseResult = ((bool)(results[0]));
            EditPhraseResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void EditPhraseAsync(Phrase phrase) {
            this.EditPhraseAsync(phrase, null);
        }
        
        /// <remarks/>
        public void EditPhraseAsync(Phrase phrase, object userState) {
            if ((this.EditPhraseOperationCompleted == null)) {
                this.EditPhraseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEditPhraseOperationCompleted);
            }
            this.InvokeAsync("EditPhrase", new object[] {
                        phrase}, this.EditPhraseOperationCompleted, userState);
        }
        
        private void OnEditPhraseOperationCompleted(object arg) {
            if ((this.EditPhraseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EditPhraseCompleted(this, new EditPhraseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IPhraseService/DeletePhrase", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DeletePhrase(int id, [System.Xml.Serialization.XmlIgnoreAttribute()] bool idSpecified, out bool DeletePhraseResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool DeletePhraseResultSpecified) {
            object[] results = this.Invoke("DeletePhrase", new object[] {
                        id,
                        idSpecified});
            DeletePhraseResult = ((bool)(results[0]));
            DeletePhraseResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void DeletePhraseAsync(int id, bool idSpecified) {
            this.DeletePhraseAsync(id, idSpecified, null);
        }
        
        /// <remarks/>
        public void DeletePhraseAsync(int id, bool idSpecified, object userState) {
            if ((this.DeletePhraseOperationCompleted == null)) {
                this.DeletePhraseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeletePhraseOperationCompleted);
            }
            this.InvokeAsync("DeletePhrase", new object[] {
                        id,
                        idSpecified}, this.DeletePhraseOperationCompleted, userState);
        }
        
        private void OnDeletePhraseOperationCompleted(object arg) {
            if ((this.DeletePhraseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeletePhraseCompleted(this, new DeletePhraseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/PopCornOneWebApp.Models")]
    public partial class Phrase {
        
        private int autorIdField;
        
        private bool autorIdFieldSpecified;
        
        private int originIdField;
        
        private bool originIdFieldSpecified;
        
        private int translationIdField;
        
        private bool translationIdFieldSpecified;
        
        private int phraseIdField;
        
        private bool phraseIdFieldSpecified;
        
        /// <remarks/>
        public int AutorId {
            get {
                return this.autorIdField;
            }
            set {
                this.autorIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AutorIdSpecified {
            get {
                return this.autorIdFieldSpecified;
            }
            set {
                this.autorIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int OriginId {
            get {
                return this.originIdField;
            }
            set {
                this.originIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OriginIdSpecified {
            get {
                return this.originIdFieldSpecified;
            }
            set {
                this.originIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int TranslationId {
            get {
                return this.translationIdField;
            }
            set {
                this.translationIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TranslationIdSpecified {
            get {
                return this.translationIdFieldSpecified;
            }
            set {
                this.translationIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int phraseId {
            get {
                return this.phraseIdField;
            }
            set {
                this.phraseIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool phraseIdSpecified {
            get {
                return this.phraseIdFieldSpecified;
            }
            set {
                this.phraseIdFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void DisplayPhrasesCompletedEventHandler(object sender, DisplayPhrasesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DisplayPhrasesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DisplayPhrasesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Phrase[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Phrase[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void CreatePhraseCompletedEventHandler(object sender, CreatePhraseCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreatePhraseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreatePhraseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int CreatePhraseResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool CreatePhraseResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void EditPhraseCompletedEventHandler(object sender, EditPhraseCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EditPhraseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EditPhraseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool EditPhraseResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool EditPhraseResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void DeletePhraseCompletedEventHandler(object sender, DeletePhraseCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeletePhraseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeletePhraseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool DeletePhraseResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool DeletePhraseResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
}

#pragma warning restore 1591