//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.544
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.544.
// 
#pragma warning disable 1591

namespace Core.TranslationReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_ITranslationService", Namespace="http://tempuri.org/")]
    public partial class TranslationServiceClient : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback DisplayTranslationsOperationCompleted;
        
        private System.Threading.SendOrPostCallback DisplayTranslationsByPhraseIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback DisplayTranslationByLexiconOperationCompleted;
        
        private System.Threading.SendOrPostCallback DisplayTranslationByFirstLetterOperationCompleted;
        
        private System.Threading.SendOrPostCallback DisplayTranslationByLanguageOperationCompleted;
        
        private System.Threading.SendOrPostCallback DisplayAllLexicalByLanguageOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateTranslationOperationCompleted;
        
        private System.Threading.SendOrPostCallback EditTranslationOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteTranslationOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public TranslationServiceClient() {
            this.Url = "http://192.168.75.103:59027/WebServices/TranslationService.svc";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event DisplayTranslationsCompletedEventHandler DisplayTranslationsCompleted;
        
        /// <remarks/>
        public event DisplayTranslationsByPhraseIdCompletedEventHandler DisplayTranslationsByPhraseIdCompleted;
        
        /// <remarks/>
        public event DisplayTranslationByLexiconCompletedEventHandler DisplayTranslationByLexiconCompleted;
        
        /// <remarks/>
        public event DisplayTranslationByFirstLetterCompletedEventHandler DisplayTranslationByFirstLetterCompleted;
        
        /// <remarks/>
        public event DisplayTranslationByLanguageCompletedEventHandler DisplayTranslationByLanguageCompleted;
        
        /// <remarks/>
        public event DisplayAllLexicalByLanguageCompletedEventHandler DisplayAllLexicalByLanguageCompleted;
        
        /// <remarks/>
        public event CreateTranslationCompletedEventHandler CreateTranslationCompleted;
        
        /// <remarks/>
        public event EditTranslationCompletedEventHandler EditTranslationCompleted;
        
        /// <remarks/>
        public event DeleteTranslationCompletedEventHandler DeleteTranslationCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ITranslationService/DisplayTranslations", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/PopCornOneWebApp.Models")]
        public Translation[] DisplayTranslations() {
            object[] results = this.Invoke("DisplayTranslations", new object[0]);
            return ((Translation[])(results[0]));
        }
        
        /// <remarks/>
        public void DisplayTranslationsAsync() {
            this.DisplayTranslationsAsync(null);
        }
        
        /// <remarks/>
        public void DisplayTranslationsAsync(object userState) {
            if ((this.DisplayTranslationsOperationCompleted == null)) {
                this.DisplayTranslationsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDisplayTranslationsOperationCompleted);
            }
            this.InvokeAsync("DisplayTranslations", new object[0], this.DisplayTranslationsOperationCompleted, userState);
        }
        
        private void OnDisplayTranslationsOperationCompleted(object arg) {
            if ((this.DisplayTranslationsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DisplayTranslationsCompleted(this, new DisplayTranslationsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ITranslationService/DisplayTranslationsByPhraseId", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/PopCornOneWebApp.Models")]
        public Translation[] DisplayTranslationsByPhraseId(int phraseId, [System.Xml.Serialization.XmlIgnoreAttribute()] bool phraseIdSpecified) {
            object[] results = this.Invoke("DisplayTranslationsByPhraseId", new object[] {
                        phraseId,
                        phraseIdSpecified});
            return ((Translation[])(results[0]));
        }
        
        /// <remarks/>
        public void DisplayTranslationsByPhraseIdAsync(int phraseId, bool phraseIdSpecified) {
            this.DisplayTranslationsByPhraseIdAsync(phraseId, phraseIdSpecified, null);
        }
        
        /// <remarks/>
        public void DisplayTranslationsByPhraseIdAsync(int phraseId, bool phraseIdSpecified, object userState) {
            if ((this.DisplayTranslationsByPhraseIdOperationCompleted == null)) {
                this.DisplayTranslationsByPhraseIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDisplayTranslationsByPhraseIdOperationCompleted);
            }
            this.InvokeAsync("DisplayTranslationsByPhraseId", new object[] {
                        phraseId,
                        phraseIdSpecified}, this.DisplayTranslationsByPhraseIdOperationCompleted, userState);
        }
        
        private void OnDisplayTranslationsByPhraseIdOperationCompleted(object arg) {
            if ((this.DisplayTranslationsByPhraseIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DisplayTranslationsByPhraseIdCompleted(this, new DisplayTranslationsByPhraseIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ITranslationService/DisplayTranslationByLexicon", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/PopCornOneWebApp.Models")]
        public Translation[] DisplayTranslationByLexicon([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string lexicon, int languageId, [System.Xml.Serialization.XmlIgnoreAttribute()] bool languageIdSpecified) {
            object[] results = this.Invoke("DisplayTranslationByLexicon", new object[] {
                        lexicon,
                        languageId,
                        languageIdSpecified});
            return ((Translation[])(results[0]));
        }
        
        /// <remarks/>
        public void DisplayTranslationByLexiconAsync(string lexicon, int languageId, bool languageIdSpecified) {
            this.DisplayTranslationByLexiconAsync(lexicon, languageId, languageIdSpecified, null);
        }
        
        /// <remarks/>
        public void DisplayTranslationByLexiconAsync(string lexicon, int languageId, bool languageIdSpecified, object userState) {
            if ((this.DisplayTranslationByLexiconOperationCompleted == null)) {
                this.DisplayTranslationByLexiconOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDisplayTranslationByLexiconOperationCompleted);
            }
            this.InvokeAsync("DisplayTranslationByLexicon", new object[] {
                        lexicon,
                        languageId,
                        languageIdSpecified}, this.DisplayTranslationByLexiconOperationCompleted, userState);
        }
        
        private void OnDisplayTranslationByLexiconOperationCompleted(object arg) {
            if ((this.DisplayTranslationByLexiconCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DisplayTranslationByLexiconCompleted(this, new DisplayTranslationByLexiconCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ITranslationService/DisplayTranslationByFirstLetter", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/PopCornOneWebApp.Models")]
        public Translation[] DisplayTranslationByFirstLetter([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string character, int languageId, [System.Xml.Serialization.XmlIgnoreAttribute()] bool languageIdSpecified) {
            object[] results = this.Invoke("DisplayTranslationByFirstLetter", new object[] {
                        character,
                        languageId,
                        languageIdSpecified});
            return ((Translation[])(results[0]));
        }
        
        /// <remarks/>
        public void DisplayTranslationByFirstLetterAsync(string character, int languageId, bool languageIdSpecified) {
            this.DisplayTranslationByFirstLetterAsync(character, languageId, languageIdSpecified, null);
        }
        
        /// <remarks/>
        public void DisplayTranslationByFirstLetterAsync(string character, int languageId, bool languageIdSpecified, object userState) {
            if ((this.DisplayTranslationByFirstLetterOperationCompleted == null)) {
                this.DisplayTranslationByFirstLetterOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDisplayTranslationByFirstLetterOperationCompleted);
            }
            this.InvokeAsync("DisplayTranslationByFirstLetter", new object[] {
                        character,
                        languageId,
                        languageIdSpecified}, this.DisplayTranslationByFirstLetterOperationCompleted, userState);
        }
        
        private void OnDisplayTranslationByFirstLetterOperationCompleted(object arg) {
            if ((this.DisplayTranslationByFirstLetterCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DisplayTranslationByFirstLetterCompleted(this, new DisplayTranslationByFirstLetterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ITranslationService/DisplayTranslationByLanguage", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/PopCornOneWebApp.Models")]
        public Translation[] DisplayTranslationByLanguage(int languageId, [System.Xml.Serialization.XmlIgnoreAttribute()] bool languageIdSpecified) {
            object[] results = this.Invoke("DisplayTranslationByLanguage", new object[] {
                        languageId,
                        languageIdSpecified});
            return ((Translation[])(results[0]));
        }
        
        /// <remarks/>
        public void DisplayTranslationByLanguageAsync(int languageId, bool languageIdSpecified) {
            this.DisplayTranslationByLanguageAsync(languageId, languageIdSpecified, null);
        }
        
        /// <remarks/>
        public void DisplayTranslationByLanguageAsync(int languageId, bool languageIdSpecified, object userState) {
            if ((this.DisplayTranslationByLanguageOperationCompleted == null)) {
                this.DisplayTranslationByLanguageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDisplayTranslationByLanguageOperationCompleted);
            }
            this.InvokeAsync("DisplayTranslationByLanguage", new object[] {
                        languageId,
                        languageIdSpecified}, this.DisplayTranslationByLanguageOperationCompleted, userState);
        }
        
        private void OnDisplayTranslationByLanguageOperationCompleted(object arg) {
            if ((this.DisplayTranslationByLanguageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DisplayTranslationByLanguageCompleted(this, new DisplayTranslationByLanguageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ITranslationService/DisplayAllLexicalByLanguage", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] DisplayAllLexicalByLanguage(int languageId, [System.Xml.Serialization.XmlIgnoreAttribute()] bool languageIdSpecified) {
            object[] results = this.Invoke("DisplayAllLexicalByLanguage", new object[] {
                        languageId,
                        languageIdSpecified});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void DisplayAllLexicalByLanguageAsync(int languageId, bool languageIdSpecified) {
            this.DisplayAllLexicalByLanguageAsync(languageId, languageIdSpecified, null);
        }
        
        /// <remarks/>
        public void DisplayAllLexicalByLanguageAsync(int languageId, bool languageIdSpecified, object userState) {
            if ((this.DisplayAllLexicalByLanguageOperationCompleted == null)) {
                this.DisplayAllLexicalByLanguageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDisplayAllLexicalByLanguageOperationCompleted);
            }
            this.InvokeAsync("DisplayAllLexicalByLanguage", new object[] {
                        languageId,
                        languageIdSpecified}, this.DisplayAllLexicalByLanguageOperationCompleted, userState);
        }
        
        private void OnDisplayAllLexicalByLanguageOperationCompleted(object arg) {
            if ((this.DisplayAllLexicalByLanguageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DisplayAllLexicalByLanguageCompleted(this, new DisplayAllLexicalByLanguageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ITranslationService/CreateTranslation", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CreateTranslation([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Translation translation, out bool CreateTranslationResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool CreateTranslationResultSpecified) {
            object[] results = this.Invoke("CreateTranslation", new object[] {
                        translation});
            CreateTranslationResult = ((bool)(results[0]));
            CreateTranslationResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void CreateTranslationAsync(Translation translation) {
            this.CreateTranslationAsync(translation, null);
        }
        
        /// <remarks/>
        public void CreateTranslationAsync(Translation translation, object userState) {
            if ((this.CreateTranslationOperationCompleted == null)) {
                this.CreateTranslationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateTranslationOperationCompleted);
            }
            this.InvokeAsync("CreateTranslation", new object[] {
                        translation}, this.CreateTranslationOperationCompleted, userState);
        }
        
        private void OnCreateTranslationOperationCompleted(object arg) {
            if ((this.CreateTranslationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateTranslationCompleted(this, new CreateTranslationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ITranslationService/EditTranslation", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void EditTranslation([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Translation translation, out bool EditTranslationResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool EditTranslationResultSpecified) {
            object[] results = this.Invoke("EditTranslation", new object[] {
                        translation});
            EditTranslationResult = ((bool)(results[0]));
            EditTranslationResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void EditTranslationAsync(Translation translation) {
            this.EditTranslationAsync(translation, null);
        }
        
        /// <remarks/>
        public void EditTranslationAsync(Translation translation, object userState) {
            if ((this.EditTranslationOperationCompleted == null)) {
                this.EditTranslationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEditTranslationOperationCompleted);
            }
            this.InvokeAsync("EditTranslation", new object[] {
                        translation}, this.EditTranslationOperationCompleted, userState);
        }
        
        private void OnEditTranslationOperationCompleted(object arg) {
            if ((this.EditTranslationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EditTranslationCompleted(this, new EditTranslationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ITranslationService/DeleteTranslation", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DeleteTranslation(int id, [System.Xml.Serialization.XmlIgnoreAttribute()] bool idSpecified, out bool DeleteTranslationResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool DeleteTranslationResultSpecified) {
            object[] results = this.Invoke("DeleteTranslation", new object[] {
                        id,
                        idSpecified});
            DeleteTranslationResult = ((bool)(results[0]));
            DeleteTranslationResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void DeleteTranslationAsync(int id, bool idSpecified) {
            this.DeleteTranslationAsync(id, idSpecified, null);
        }
        
        /// <remarks/>
        public void DeleteTranslationAsync(int id, bool idSpecified, object userState) {
            if ((this.DeleteTranslationOperationCompleted == null)) {
                this.DeleteTranslationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteTranslationOperationCompleted);
            }
            this.InvokeAsync("DeleteTranslation", new object[] {
                        id,
                        idSpecified}, this.DeleteTranslationOperationCompleted, userState);
        }
        
        private void OnDeleteTranslationOperationCompleted(object arg) {
            if ((this.DeleteTranslationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteTranslationCompleted(this, new DeleteTranslationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/PopCornOneWebApp.Models")]
    public partial class Translation {
        
        private int languageIdField;
        
        private bool languageIdFieldSpecified;
        
        private string lexiconField;
        
        private bool phraseByDefaultField;
        
        private bool phraseByDefaultFieldSpecified;
        
        private int phraseIdField;
        
        private bool phraseIdFieldSpecified;
        
        private string translationContentField;
        
        private string translationDescriptionField;
        
        private string translationFirstLetterField;
        
        private int translationIdField;
        
        private bool translationIdFieldSpecified;
        
        /// <remarks/>
        public int LanguageId {
            get {
                return this.languageIdField;
            }
            set {
                this.languageIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LanguageIdSpecified {
            get {
                return this.languageIdFieldSpecified;
            }
            set {
                this.languageIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Lexicon {
            get {
                return this.lexiconField;
            }
            set {
                this.lexiconField = value;
            }
        }
        
        /// <remarks/>
        public bool PhraseByDefault {
            get {
                return this.phraseByDefaultField;
            }
            set {
                this.phraseByDefaultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PhraseByDefaultSpecified {
            get {
                return this.phraseByDefaultFieldSpecified;
            }
            set {
                this.phraseByDefaultFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int PhraseId {
            get {
                return this.phraseIdField;
            }
            set {
                this.phraseIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PhraseIdSpecified {
            get {
                return this.phraseIdFieldSpecified;
            }
            set {
                this.phraseIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TranslationContent {
            get {
                return this.translationContentField;
            }
            set {
                this.translationContentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TranslationDescription {
            get {
                return this.translationDescriptionField;
            }
            set {
                this.translationDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TranslationFirstLetter {
            get {
                return this.translationFirstLetterField;
            }
            set {
                this.translationFirstLetterField = value;
            }
        }
        
        /// <remarks/>
        public int TranslationId {
            get {
                return this.translationIdField;
            }
            set {
                this.translationIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TranslationIdSpecified {
            get {
                return this.translationIdFieldSpecified;
            }
            set {
                this.translationIdFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void DisplayTranslationsCompletedEventHandler(object sender, DisplayTranslationsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DisplayTranslationsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DisplayTranslationsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Translation[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Translation[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void DisplayTranslationsByPhraseIdCompletedEventHandler(object sender, DisplayTranslationsByPhraseIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DisplayTranslationsByPhraseIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DisplayTranslationsByPhraseIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Translation[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Translation[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void DisplayTranslationByLexiconCompletedEventHandler(object sender, DisplayTranslationByLexiconCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DisplayTranslationByLexiconCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DisplayTranslationByLexiconCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Translation[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Translation[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void DisplayTranslationByFirstLetterCompletedEventHandler(object sender, DisplayTranslationByFirstLetterCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DisplayTranslationByFirstLetterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DisplayTranslationByFirstLetterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Translation[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Translation[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void DisplayTranslationByLanguageCompletedEventHandler(object sender, DisplayTranslationByLanguageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DisplayTranslationByLanguageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DisplayTranslationByLanguageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Translation[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Translation[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void DisplayAllLexicalByLanguageCompletedEventHandler(object sender, DisplayAllLexicalByLanguageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DisplayAllLexicalByLanguageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DisplayAllLexicalByLanguageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CreateTranslationCompletedEventHandler(object sender, CreateTranslationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateTranslationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateTranslationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool CreateTranslationResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool CreateTranslationResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void EditTranslationCompletedEventHandler(object sender, EditTranslationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EditTranslationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EditTranslationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool EditTranslationResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool EditTranslationResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void DeleteTranslationCompletedEventHandler(object sender, DeleteTranslationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteTranslationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteTranslationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool DeleteTranslationResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool DeleteTranslationResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
}

#pragma warning restore 1591